services:
  postgres:
    image: postgres:16-alpine
    container_name: coleira-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: coleira
      POSTGRES_PASSWORD: coleira
      POSTGRES_DB: coleira
    ports:
      - '5433:5432'
    volumes:
      - coleira_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U coleira -d coleira']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: coleira-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - coleira_redis_data:/data
    command: ['redis-server', '--appendonly', 'yes']
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  coleira_pg_data:
  coleira_redis_data:
